server:
  port: 8090

spring:
  datasource:
#    url: jdbc:mysql://192.168.20.28:3306/test
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

appDescription: "estas en modo de desarrollo"
appVersion: "1.0.0"